const db = [
  {
    id: 1,
    companyId: 1,
    createdBy: 1,
    title: "Software Developer (C++/Qt Framework)",
    salary: "0",
    responsibilities: [
      "As part of the team, you will develop and maintain cross-platform applications (Windows and Android) using Qt framework for Restaurant Solution (POS systems, tablet order, etc).",
      "Collaborate with the team to understand project requirements and translate them into technical solutions.",
      "Conduct testing and debugging of Qt applications to ensure optimal performance and reliability.",
    ],
    skills: [
      "Experience in C++ software development, with a strong emphasis on Qt and QML.",
      "Experience in OOP (Object Oriented Programming).",
    ],
    extends: [
      "Experience working with RESTful APIs for data exchange between client and server applications.",
      "Familiarity with SQLite database management system, including database design, querying, and integration within Qt/QML applications.",
    ],
    welfare: [
      "Salary is paid according to employee capacity",
      "Salary adjustment 1-2 times a year (KPI)",
    ],
    experienceYearsMin: "0",
    experienceYearsMax: "0",
    level: "all",
    type: "office",
    typeContract: "fulltime",
    techs: ["C++", "Software Engineer"],
    interviewProcess: [
      "Vòng 1: PV qua điện thoại",
      "Vòng 2: PV trực tiếp với Tech Lead (Bài test tùy vị trí)",
      "Vòng 3: Deal lương",
    ],
    createdAt: "2024-03-29T12:00:00.000Z",
    updatedAt: "2024-03-29T12:00:00.000Z",
  },
  {
    id: 2,
    companyId: 2,
    createdBy: 2,
    title: "Frontend Developer (React.js)",
    salary: "0",
    responsibilities: [
      "Develop user-facing features using React.js framework.",
      "Design and implement user interfaces for web applications.",
      "Collaborate with backend developers to integrate frontend with server-side logic.",
    ],
    skills: [
      "Proficiency in HTML, CSS, and JavaScript.",
      "Experience with React.js and its ecosystem (Redux, React Router, etc).",
    ],
    extends: [
      "Knowledge of RESTful APIs and integration with frontend applications.",
      "Understanding of version control systems (e.g., Git) and continuous integration/deployment pipelines.",
    ],
    welfare: [
      "Competitive salary based on skills and experience.",
      "Opportunities for career growth and professional development.",
    ],
    experienceYearsMin: "1",
    experienceYearsMax: "3",
    level: "mid",
    type: "office",
    typeContract: "fulltime",
    techs: ["React.js", "Frontend Developer"],
    interviewProcess: [
      "Phone screening interview.",
      "Technical interview with frontend team lead (may include coding test).",
      "Final interview with HR for negotiation.",
    ],
    createdAt: "2024-03-29T12:00:00.000Z",
    updatedAt: "2024-03-29T12:00:00.000Z",
  },
  {
    id: 3,
    companyId: 2,
    createdBy: 2,
    title: "Backend Developer (Node.js)",
    salary: "0",
    responsibilities: [
      "Develop and maintain server-side logic using Node.js.",
      "Implement data storage solutions using databases like MongoDB or PostgreSQL.",
      "Collaborate with frontend developers to integrate frontend components with backend services.",
    ],
    skills: [
      "Proficiency in JavaScript and Node.js runtime environment.",
      "Experience with backend frameworks/libraries (e.g., Express.js, NestJS).",
    ],
    extends: [
      "Understanding of database systems and query optimization techniques.",
      "Knowledge of RESTful API design principles and best practices.",
    ],
    welfare: [
      "Competitive salary based on skills and experience.",
      "Flexible working hours and remote work options.",
    ],
    experienceYearsMin: "2",
    experienceYearsMax: "4",
    level: "senior",
    type: "office",
    typeContract: "fulltime",
    techs: ["Node.js", "Backend Developer"],
    interviewProcess: [
      "Initial screening interview.",
      "Technical interview with backend team lead (may include coding test).",
      "Final interview with HR for negotiation.",
    ],
    createdAt: "2024-03-29T12:00:00.000Z",
    updatedAt: "2024-03-29T12:00:00.000Z",
  },
  {
    id: 4,
    companyId: 1,
    createdBy: 1,
    title: "Data Scientist",
    salary: "0",
    responsibilities: [
      "Develop predictive models and machine learning algorithms.",
      "Analyze large datasets to identify patterns and trends.",
      "Collaborate with business stakeholders to understand requirements and deliver actionable insights.",
    ],
    skills: [
      "Strong background in statistics, mathematics, and machine learning.",
      "Proficiency in programming languages like Python or R.",
    ],
    extends: [
      "Experience with data visualization tools (e.g., Matplotlib, Seaborn, Tableau).",
      "Knowledge of big data technologies (e.g., Hadoop, Spark) is a plus.",
    ],
    welfare: [
      "Competitive salary based on skills and experience.",
      "Opportunities for career advancement in data science field.",
    ],
    experienceYearsMin: "3",
    experienceYearsMax: "5",
    level: "senior",
    type: "office",
    typeContract: "fulltime",
    techs: ["Data Scientist"],
    interviewProcess: [
      "Initial screening interview.",
      "Technical interview with data science team lead (may include coding test).",
      "Final interview with HR for negotiation.",
    ],
    createdAt: "2024-03-29T12:00:00.000Z",
    updatedAt: "2024-03-29T12:00:00.000Z",
  },
  {
    id: 5,
    companyId: 3,
    createdBy: 3,
    title: "DevOps Engineer",
    salary: "0",
    responsibilities: [
      "Automate and streamline development, testing, and deployment processes.",
      "Manage infrastructure and configuration using tools like Docker and Kubernetes.",
      "Monitor system performance and troubleshoot issues.",
    ],
    skills: [
      "Experience with infrastructure as code tools (e.g., Terraform, CloudFormation).",
      "Proficiency in scripting languages like Bash or Python.",
    ],
    extends: [
      "Understanding of CI/CD pipelines and version control systems (e.g., Git).",
      "Familiarity with cloud platforms like AWS, Azure, or GCP.",
    ],
    welfare: [
      "Competitive salary based on skills and experience.",
      "Opportunities for professional development and training.",
    ],
    experienceYearsMin: "2",
    experienceYearsMax: "4",
    level: "mid",
    type: "office",
    typeContract: "fulltime",
    techs: ["DevOps Engineer"],
    interviewProcess: [
      "Phone screening interview.",
      "Technical interview with DevOps team lead (may include coding test).",
      "Final interview with HR for negotiation.",
    ],
    createdAt: "2024-03-29T12:00:00.000Z",
    updatedAt: "2024-03-29T12:00:00.000Z",
  },
];

module.exports = { db };
