pipeline {
    agent any

    tools {
        nodejs '20.13.1' // Use the configured Node.js version
    }

    stages {

        // stage('Run Tests') {
        //     steps {
        //         script {
        //           dir('express_service/services/job'){
        //             sh 'npm i'
        //             sh 'cp .env.example .env'
        //             sh 'npm test -- --forceExit'
        //           }
        //         }
        //     }
        // }


        stage('Deploy') {
            steps {
                script {
                    sshagent(credentials:['topdev-vm']) {
                        // Ensure the .ssh directory exists and then add the host key to known_hosts
                        sh """
                        mkdir -p ~/.ssh
                        ssh-keyscan -H 20.205.143.124 >> ~/.ssh/known_hosts
                        """

                        // Deployment commands
                        sh """    
                        ssh -t azureuser@20.205.143.124 'sudo rm -rf TopDevCloneBE && git clone https://github.com/kuroneko2002/TopDevCloneBE.git && cd TopDevCloneBE/express_service && docker stack rm express_service && docker system prune -a -f && sleep 10s && docker image prune -a -f && sleep 10s && docker compose build && docker tag express_service-authentication topdev11/authentication:latest && docker push topdev11/authentication && docker tag express_service-job topdev11/job:latest && docker push topdev11/job && docker tag express_service-user topdev11/user:latest && docker push topdev11/user && docker tag express_service-application topdev11/application:latest && docker push topdev11/application && docker tag express_service-gateway topdev11/gateway:latest && docker push topdev11/gateway && docker tag express_service-nginx-loadbalancer topdev11/nginx-loadbalancer:latest && docker push topdev11/nginx-loadbalancer'      
                        """
                    }
                }
            }
        }

        stage('deploy swarm') {
            steps {
                script {
                    sshagent(credentials:['topdev-vm']) {
                        // Ensure the .ssh directory exists and then add the host key to known_hosts
                        sh """
                        mkdir -p ~/.ssh
                        ssh-keyscan -H 20.205.143.124 >> ~/.ssh/known_hosts
                        """

                        // Deployment commands
                        sh """
                        ssh -t azureuser@20.205.143.124 'cd TopDevCloneBE/express_service && docker system prune -f && sleep 10s && docker stack deploy -c docker-deploy.yml express_service'
                        """
                    }
                }
            }
        }
    }
}